# Generated by Django 4.1.7 on 2023-06-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_score_usertag_value_userentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reviewed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
