# Generated by Django 4.1.7 on 2023-06-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avg_rating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
