# Generated by Django 4.1.7 on 2023-06-21 22:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile_avg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avg_rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0'), max_digits=3, null=True),
        ),
    ]
