# Generated by Django 4.1.7 on 2023-06-22 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_profile_avg_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertag',
            old_name='value',
            new_name='sum_scores',
        ),
        migrations.AddField(
            model_name='usertag',
            name='count',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
