# Generated by Django 4.1.7 on 2023-06-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_value_usertag_sum_scores_usertag_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertag',
            name='sum_scores',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
