# Generated by Django 4.1.7 on 2023-06-26 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_playlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
