# Generated by Django 4.1.7 on 2023-08-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0041_remove_director_image'),
        ('users', '0021_profile_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='seen',
            field=models.ManyToManyField(blank=True, related_name='seen_by', to='content.entity'),
        ),
    ]
