# Generated by Django 4.1.7 on 2023-05-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='genres',
            field=models.ManyToManyField(related_name='GenreEntityLinker', to='content.genre'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='entities',
            field=models.ManyToManyField(related_name='GenreEntityLinker', to='content.entity'),
        ),
    ]
