# Generated by Django 4.1.7 on 2023-05-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_entity_genres_alter_genre_entities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='image',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='overall_rating1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='overall_rating2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='overall_rating3',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='overall_rating4',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='overall_rating5',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='overall_score',
            field=models.IntegerField(null=True),
        ),
    ]
