# Generated by Django 4.1.7 on 2023-05-19 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_entity_description_alter_entity_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='mediums',
            new_name='medium',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='genres',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='mediums',
            new_name='medium',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='entities',
            new_name='entity',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='mediums',
            new_name='medium',
        ),
    ]
