# Generated by Django 4.1.7 on 2023-05-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_rename_mediums_category_medium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='overall_rating1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='overall_rating2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='overall_rating3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='overall_rating4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='overall_rating5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='overall_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
