# Generated by Django 4.1.7 on 2023-05-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_entity_description_alter_entity_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='entity',
            field=models.ManyToManyField(blank=True, related_name='GenreEntityLinker', to='content.entity'),
        ),
    ]
