# Generated by Django 4.1.7 on 2023-05-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_genre_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
