# Generated by Django 4.1.7 on 2023-05-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_entity_description_alter_entity_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='api_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='slug_field',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
