# Generated by Django 4.1.7 on 2023-05-27 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_entity_api_id_entity_slug_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='added_to_playlist',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='clean',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='clicked',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='reviewed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='searched',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EntityActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_character', models.CharField(blank=True, max_length=500, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.actor')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.entity')),
            ],
        ),
    ]
