# Generated by Django 4.1.7 on 2023-05-27 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_actor_entity_added_to_playlist_entity_clean_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/')),
                ('name', models.CharField(max_length=100)),
                ('descriptive', models.BooleanField(blank=True, null=True)),
                ('emotional', models.BooleanField(blank=True, null=True)),
                ('medium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.medium')),
            ],
        ),
        migrations.CreateModel(
            name='EntityTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='content.entity')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='content.tag')),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='tag',
            field=models.ManyToManyField(through='content.EntityTag', to='content.tag'),
        ),
    ]
