# Generated by Django 4.1.7 on 2023-05-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_tag_entitytag_entity_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='overall_rating1',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='overall_rating2',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='overall_rating3',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='overall_rating4',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='overall_rating5',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
