# Generated by Django 4.1.7 on 2023-05-29 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_emotion_remove_tag_descriptive_remove_tag_emotional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='medium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='content.medium'),
        ),
    ]
