# Generated by Django 4.1.7 on 2023-05-31 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_alter_entity_medium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='emotion',
        ),
        migrations.RenameModel(
            old_name='Emotion',
            new_name='BaseEmotion',
        ),
        migrations.CreateModel(
            name='DerivedEmotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_emotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='content.baseemotion')),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='derived_emotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='content.derivedemotion'),
        ),
    ]
