# Generated by Django 4.1.7 on 2023-05-31 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_remove_tag_emotion_rename_emotion_baseemotion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='base_emotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='content.baseemotion'),
        ),
    ]
