# Generated by Django 4.1.7 on 2023-06-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_tag_base_emotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
