# Generated by Django 4.1.7 on 2023-06-06 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_category_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityactor',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='content.actor'),
        ),
        migrations.AlterField(
            model_name='entityactor',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='content.entity'),
        ),
    ]
