# Generated by Django 4.1.7 on 2023-06-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_alter_entityactor_actor_alter_entityactor_entity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='overall_rating1',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='overall_rating2',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='overall_rating3',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='overall_rating4',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='overall_rating5',
        ),
        migrations.AddField(
            model_name='entity',
            name='overall_category_rating1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='overall_category_rating2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='overall_category_rating3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='overall_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
