# Generated by Django 4.1.7 on 2023-06-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_remove_entity_overall_rating1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='sum_scores',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
