# Generated by Django 4.1.7 on 2023-06-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_alter_entitytag_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='overall_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
