# Generated by Django 4.1.7 on 2023-06-20 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_alter_entity_overall_score_alter_entity_sum_scores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='reviewed',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='sum_scores',
        ),
    ]
