# Generated by Django 4.1.7 on 2023-06-20 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_entity_reviewed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='description_full',
            new_name='plot',
        ),
    ]
