# Generated by Django 4.1.7 on 2023-06-21 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_rename_description_full_entity_plot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='overall_category_rating1',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='overall_category_rating2',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='overall_category_rating3',
        ),
    ]
