# Generated by Django 4.1.7 on 2023-06-22 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_alter_entitytag_entity_alter_entitytag_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='description',
            new_name='year',
        ),
    ]
