# Generated by Django 4.1.7 on 2023-06-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_entity_content_rating_entity_runtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='tag',
            new_name='tags',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='genre',
        ),
        migrations.AddField(
            model_name='entity',
            name='actors',
            field=models.ManyToManyField(through='content.EntityActor', to='content.actor'),
        ),
        migrations.AddField(
            model_name='entity',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, related_name='entities', to='content.genre'),
        ),
    ]
