# Generated by Django 4.1.7 on 2023-06-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0031_alter_actor_api_id_alter_entity_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='imDbRatingVotes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='api_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
