# Generated by Django 4.1.7 on 2023-06-23 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0033_alter_entity_actors_alter_entity_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityactor',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.actor'),
        ),
        migrations.AlterField(
            model_name='entityactor',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.entity'),
        ),
    ]
