# Generated by Django 4.1.7 on 2023-06-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0034_alter_entityactor_actor_alter_entityactor_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='added_to_playlist',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='clicked',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
