# Generated by Django 4.1.7 on 2023-08-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0035_alter_entity_added_to_playlist_alter_entity_clicked'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('entity', models.ManyToManyField(blank=True, related_name='Location', to='content.entity')),
            ],
        ),
    ]
