# Generated by Django 4.1.7 on 2023-08-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0036_streamingservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='streamingservices',
            field=models.ManyToManyField(blank=True, related_name='entities', to='content.streamingservice'),
        ),
        migrations.AlterField(
            model_name='streamingservice',
            name='entity',
            field=models.ManyToManyField(blank=True, related_name='streaming_services', to='content.entity'),
        ),
    ]
