# Generated by Django 4.1.7 on 2023-08-07 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0037_entity_streamingservices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamingservice',
            name='entity',
        ),
        migrations.CreateModel(
            name='EntityLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.entity')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.streamingservice')),
            ],
        ),
    ]
