# Generated by Django 4.1.7 on 2023-08-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0038_remove_streamingservice_entity_entitylocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamingservice',
            name='image',
            field=models.ImageField(null=True, upload_to='location/'),
        ),
    ]
