# Generated by Django 4.1.7 on 2023-08-11 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0040_director_entity_directors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='image',
        ),
    ]
