# Generated by Django 4.1.7 on 2023-08-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0041_remove_director_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='imdbRating',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
