# Generated by Django 4.1.7 on 2023-05-27 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_actor_entity_added_to_playlist_entity_clean_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0002_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='final_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviews', to='content.entity'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating1',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating2',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating3',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating4',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating5',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
