# Generated by Django 4.1.7 on 2023-05-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_emotion_remove_tag_descriptive_remove_tag_emotional_and_more'),
        ('reviews', '0003_review_final_score_alter_review_entity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='tags',
            field=models.ManyToManyField(related_name='reviews', to='content.tag'),
        ),
    ]
