# Generated by Django 4.1.7 on 2023-05-29 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0013_alter_entity_medium'),
        ('reviews', '0004_review_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating1',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating2',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating3',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating4',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating5',
        ),
        migrations.AddField(
            model_name='review',
            name='category_rating1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='category_rating2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='category_rating3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='category_rating4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='content.entity'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
