# Generated by Django 4.1.7 on 2023-06-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_category_order'),
        ('reviews', '0008_review_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='tags',
            field=models.ManyToManyField(blank=True, limit_choices_to={'id__lte': 5}, related_name='reviews', to='content.tag'),
        ),
    ]
