# Generated by Django 4.1.7 on 2023-06-07 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_alter_review_entity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='category_rating4',
        ),
    ]
