# Generated by Django 4.1.7 on 2023-06-22 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_remove_entity_overall_category_rating1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0014_remove_review_category_rating4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='content.entity'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
