# Generated by Django 4.1.7 on 2023-08-04 16:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0015_alter_review_entity_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='review_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
