# Generated by Django 4.1.7 on 2023-08-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_alter_review_blurb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='blurb',
            field=models.CharField(max_length=999, null=True),
        ),
    ]
