# Generated by Django 4.1.7 on 2023-08-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0019_reviewcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
