# Generated by Django 4.1.7 on 2023-08-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0004_playlist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='auto_generated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
