# Generated by Django 4.1.7 on 2023-08-15 21:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playlists', '0006_playlist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='playlist_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
